name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-
    - name: Clean up old Docker containers
      run: |
        # Remove all stopped containers
        docker container prune -f

        # Remove all unused images (dangling images)
        docker image prune -f

    - name: Build Docker image
      run: |
        # Build the Docker image
        docker build -t gcr.io/light-maker-450401-b0/bookclub-backend-service-img .

        # Get the current image digest (hash)
        IMAGE_DIGEST=$(docker images --digests --format "{{.Repository}}@{{.Digest}}" gcr.io/light-maker-450401-b0/bookclub-backend-service-img)

        # Save the image digest for future comparison
        echo $IMAGE_DIGEST > image_digest.txt
        echo "Image digest: $IMAGE_DIGEST"

    - name: Check if image has changed
      run: |
        # Retrieve the previously pushed image digest (from a previous build)
        if [ -f image_digest.txt ]; then
          PREVIOUS_DIGEST=$(cat image_digest.txt)
          echo "Previous image digest: $PREVIOUS_DIGEST"
        else
          echo "No previous digest found, pushing the image for the first time."
          exit 0
        fi

        # Compare the digests and conditionally push if different
        if [ "$IMAGE_DIGEST" != "$PREVIOUS_DIGEST" ]; then
          echo "Image has changed. Proceeding with image push."
          exit 0
        else
          echo "No changes detected in the image. Skipping image push."
          exit 1
        fi

    - name: Set up GCP credentials
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
        gcloud config set project light-maker-450401-b0
        gcloud auth configure-docker --quiet


    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/light-maker-450401-b0/bookclub-backend-service-img

    - name: SSH into GCE instance and deploy Docker container
      uses: appleboy/ssh-action@v1.2.1
      with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            ENDPOINT="metadata.google.internal/computeMetadata/v1"
            ACCOUNT="default"
            TOKEN=$(curl --silent --header "Metadata-Flavor: Google" http://${ENDPOINT}/instance/service-accounts/${ACCOUNT}/token)
            ACCESS=$(echo ${TOKEN} | grep --extended-regexp --only-matching "(ya29\.[0-9a-zA-Z._-]*)")
            HOST="https://gcr.io"
            printf ${ACCESS} | docker login ${HOST} -u oauth2accesstoken --password-stdin
            docker stop bookclub-backend-service-instance || true
            docker rm bookclub-backend-service-instance || true
            docker run -d --name bookclub-backend-service-instance -p 5000:5000 \
                -e XATA_API_KEY=${{ secrets.XATA_API_KEY }} \
                -e DATABASE_URL_POSTGRES=${{ secrets.DATABASE_URL_POSTGRES }} \
                -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
                -e DB_HOST=${{ secrets.DB_HOST }} \
                -e DB_PORT=${{ secrets.DB_PORT }} \
                -e DB_USER=${{ secrets.DB_USER }} \
                -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                -e DB_NAME=${{ secrets.DB_NAME }} \
                -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                -e JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
                -e GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }} \
                -e GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GCP_SA_KEY }} \
                --pull always gcr.io/light-maker-450401-b0/bookclub-backend-service-img